name: Deploy React Vite App to Bunny.net

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.6.1'  # Set Node.js version to 20.6.1

      - name: Install dependencies
        run: npm install

      - name: Build the project
        run: npm run build

      - name: Install Bunny CLI
        run: |
          curl -sL https://cdn.bunny.net/setup/cli | bash  # This installs Bunny CLI globally
          echo "Bunny CLI installed successfully."

      - name: Deploy to Bunny.net
        run: |
          bunny-cli login --access-key ${{ secrets.BUNNY_ACCESS_KEY }}  # Login with Bunny Access Key
          bunny-cli push ./dist --zone ${{ secrets.BUNNY_ZONE_NAME }} --path /user-dashboard  # Push to Bunny.net
        env:
          BUNNY_ACCESS_KEY: ${{ secrets.BUNNY_ACCESS_KEY }}
          BUNNY_ZONE_NAME: ${{ secrets.BUNNY_ZONE_NAME }}
