name: Deploy React Vite App to Bunny.net

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.6.1'

      - name: Install dependencies
        run: npm install

      - name: Build the project
        run: npm run build

      - name: Verify Files Before Uploading
        run: |
          # List files in the dist folder
          echo "Listing files in ./dist/"
          ls -l ./dist/

      - name: Upload files to Bunny.net
        run: |
          # Loop through all files in the dist folder and upload them
          for file in ./dist/*; do
            echo "Uploading: $file"
            curl -X PUT "https://sg.storage.bunnycdn.com/${{ secrets.BUNNY_ZONE_NAME }}/user-dashboard/$(basename $file)" \
              -H "Authorization: Bearer ${{ secrets.BUNNY_ACCESS_KEY }}" \
              --data-binary @$file
          done
        env:
          BUNNY_ACCESS_KEY: ${{ secrets.BUNNY_ACCESS_KEY }}
          BUNNY_ZONE_NAME: ${{ secrets.BUNNY_ZONE_NAME }}
