name: Deploy React Vite App to Bunny.net

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '17'  # Change from '16' to '17' or a higher version

      - name: Install dependencies
        run: npm install

      - name: Build the project 
        run: npm run build

      - name: Deploy to Bunny.net
        run: |
          curl -sL https://cdn.bunny.net/setup/cli | bash
          bunny-cli login --access-key ${{ secrets.BUNNY_ACCESS_KEY }}
          bunny-cli push ./dist --zone ${{ secrets.BUNNY_ZONE_NAME }} --path /user-dashboard
        env:
          BUNNY_ACCESS_KEY: ${{ secrets.BUNNY_ACCESS_KEY }}
          BUNNY_ZONE_NAME: ${{ secrets.BUNNY_ZONE_NAME }}
