name: Deploy React Vite App to Bunny.net

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.6.1'

      - name: Install dependencies
        run: npm install

      - name: Build the project
        run: npm run build

      - name: List build directory contents
        run: ls -R ./dist  # List all files in dist directory recursively

      - name: Upload files to Bunny.net using API
        run: |
          # Loop through all files in the dist directory and upload each one
          find ./dist -type f | while read file; do
            echo "Uploading $file"
            curl -X PUT "https://sg.storage.bunnycdn.com/${{ secrets.BUNNY_ZONE_NAME }}/user-dashboard/$(basename $file)" \
              -H "AccessKey: ${{ secrets.BUNNY_ACCESS_KEY }}" \
              --data-binary @"$file"  # Upload the current file
          done
        env:
          BUNNY_ACCESS_KEY: ${{ secrets.BUNNY_ACCESS_KEY }}
          BUNNY_ZONE_NAME: ${{ secrets.BUNNY_ZONE_NAME }}
